In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
# import tensorflow as tf
# import keras

In [2]:
oil = pd.read_csv("/Users/ishitajain/stocks-web-app/Spring-Invitation-Datathon-2024/clean_data/cleaned_merged_emissions_consumption.csv")
temp = pd.read_csv("/Users/ishitajain/stocks-web-app/Spring-Invitation-Datathon-2024/clean_data/temp.csv")

/var/folders/wk/48ywwld12k3b18wmjf4yr1080000gn/T/ipykernel_56599/713681304.py:1: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  oil = pd.read_csv("/Users/ishitajain/stocks-web-app/Spring-Invitation-Datathon-2024/clean_data/cleaned_merged_emissions_consumption.csv")

In [6]:
oil['Energy Type'].value_counts()

Total                                 18589
Distillate Fuel Oil                    6721
Coal                                   6698
Natural Gas                            6406
Residual Fuel Oil                      5499
Kerosene                               4277
Motor Gasoline                         4277
Petroleum Coke                         3893
Lubricants                             3055
Hydrocarbon Gas Liquids (HGL)          3055
Biomass                                2959
Electricity                            2444
Wood Energy                            2444
Propane                                2444
Geothermal Energy                      2287
Aviation Gasoline                      1833
Jet Fuel                               1833
Total Renewable Energy                 1833
Solar Energy                           1736
Hydroelectric Power                    1633
Waste Energy                           1545
Wind Energy                            1329
Other                                  1222
Fuel Ethanol, Excluding Denaturant     1030
Natural Gas - Non-CHP                   685
Natural Gas - Pipelines and Distro      684
Renewable Energy                        611
Propane/Propylene                       611
Biomass Waste                           611
Wood                                    611
Coal Coke                               611
Asphalt and Road Oil                    611
Propylene                               611
Other Petroleum Products                611
Coal - Non-CHP                          599
Coal - Other - Total                    599
Biomass Losses and Co-products          515
Biofuels                                515
Fuel Ethanol                            515
Natural Gas - CHP                       453
Natural Gas - Vehicle Fuel              440
Non-Biomass Waste                       419
Coal - CHP                              407
Biodiesel                               275
Other Products                           35
Name: Energy Type, dtype: int64

In [5]:
oil

,EIA_ID,YYYYMM,Date,Value,Column_Order,Description,Unit,Energy Type,Energy Class,Sector
0,DFRCPUS,197301,1/1/1973,1706.943,1,Distillate Fuel Oil Consumed by the Residentia...,Thousand Barrels per Day,Distillate Fuel Oil,Petroleum,Residential
1,DFRCPUS,197302,2/1/1973,1614.436,1,Distillate Fuel Oil Consumed by the Residentia...,Thousand Barrels per Day,Distillate Fuel Oil,Petroleum,Residential
2,DFRCPUS,197303,3/1/1973,1140.521,1,Distillate Fuel Oil Consumed by the Residentia...,Thousand Barrels per Day,Distillate Fuel Oil,Petroleum,Residential
3,DFRCPUS,197304,4/1/1973,824.604,1,Distillate Fuel Oil Consumed by the Residentia...,Thousand Barrels per Day,Distillate Fuel Oil,Petroleum,Residential
4,DFRCPUS,197305,5/1/1973,676.745,1,Distillate Fuel Oil Consumed by the Residentia...,Thousand Barrels per Day,Distillate Fuel Oil,Petroleum,Residential
...,...,...,...,...,...,...,...,...,...,...
100066,BMTCEUS,202307,7/1/2023,26.54,11,Biomass CO2 Emissions,Million Metric Tons of Carbon Dioxide,Total,Biomass,Overall
100067,BMTCEUS,202308,8/1/2023,27.032,11,Biomass CO2 Emissions,Million Metric Tons of Carbon Dioxide,Total,Biomass,Overall
100068,BMTCEUS,202309,9/1/2023,25.438,11,Biomass CO2 Emissions,Million Metric Tons of Carbon Dioxide,Total,Biomass,Overall
100069,BMTCEUS,202310,10/1/2023,26.215,11,Biomass CO2 Emissions,Million Metric Tons of Carbon Dioxide,Total,Biomass,Overall
100070,BMTCEUS,202311,11/1/2023,26.109,11,Biomass CO2 Emissions,Million Metric Tons of Carbon Dioxide,Total,Biomass,Overall

In [10]:
temp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1997 entries, 0 to 1996
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  1997 non-null   int64
 1   anomaly     1997 non-null   float64
 2   date        1997 non-null   object
dtypes: float64(1), int64(1), object(1)
memory usage: 46.9+ KB

In [12]:
temp[1]

KeyError: 1